## Stage 1: Base
FROM node:22-alpine AS base

WORKDIR /usr/src/app

ARG JWT_KEY
ENV JWT_KEY=${JWT_KEY}

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

## Stage 2: Instalación de dependencias
FROM base AS dep

COPY package.json ./
COPY package-lock.json ./

RUN npm install

## STage 3: Build

FROM base AS build

COPY --from=dep /usr/src/app/node_modules ./node_modules

COPY . .
RUN npx prisma migrate deploy
RUN npx prisma generate
RUN npm run build
RUN npm ci -f --only=production && npm cache clean --force

## Stage 4: Imagen final

FROM base AS prod

ENV NODE_ENV=production

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

USER node
EXPOSE 3000

CMD ["node", "dist/main.js"]