## Stage 1: Depedencias
FROM node:22-alpine AS dep

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

## Stage 2: Aplicación

FROM node:22-alpine AS build

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/src/app

COPY --from=dep /usr/src/app/node_modules ./node_modules

COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

## Stage 3: Imagen final

FROM node:22-alpine AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

COPY --from=build /usr/src/app/dist ./dist

ARG JWT_KEY
ENV JWT_KEY=${JWT_KEY}

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["node", "dist/main.js"]

