services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-blog
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
  api:
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: dockerfile
    image: blog-compose
    volumes:
      - ./src:/usr/src/app/src
    command: npm run docker:start
    environment:
      - DATABASE_URL=mysql://root:${DATABASE_PASSWORD}@mysql-db:3306/prismeico?schema=public
      - JWT_KEY=${JWT_KEY}
      - NODE_ENV=development
      - PORT=${PORT}
    ports:
      - 3000:3000
    #tty: true
    #stdin_open: true
    #develop:
    #  watch:
    #    - action: sync
          # path: ./src
          # target: /usr/src/app/src
