name: pipeline

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Get code'
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci --no-fund --no-audit
      - name: Linter
        run: npm run lint
  build: ## acá debería construir el dockerfile?
    needs: [linter]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - name: Mysql?
        run: mysql --version
      - name: Restart mysql
        run: sudo systemctl restart mysql
      - name: status mysql
        run: sudo systemctl status mysql
      - name: Install dependencies
        run: npm ci --no-fund --no-audit
      - name: Build application
        run: npm run build
      - name: ls
        run: ls -al
      - name: Creating artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  test: ## test debería ser antes que build?
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test
