name: pipeline

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Get code'
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci --no-fund --no-audit
      - name: Linter
        run: npm run lint
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - name: Restart mysql
        run: sudo systemctl restart mysql
      - name: Install dependencies
        run: npm ci --no-fund --no-audit
      - name: status mysql
        run: sudo systemctl status mysql
      - name: Delete migration
        run: rm -rf prisma/migrations
      - name: Migrate database
        run: npm run migrate -- --name init
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Generate prisma client
        run: npm run client
      - name: Test
        run: npm run test -- --silent
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
